# Generated by Django 5.2.1 on 2025-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indor'), ('Outdoor', 'Outdoor')], max_length=100, null=True),
        ),
    ]
